# Generated by Django 4.2.4 on 2023-08-07 07:06

import datetime
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0002_alter_card_review_date_alter_deck_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='date_created',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='card',
            name='review_date',
            field=models.DateField(default=datetime.datetime(2023, 8, 8, 10, 36, 48, 904540)),
        ),
    ]
