# Generated by Django 4.2.4 on 2023-08-07 07:20

import datetime
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0003_card_date_created_alter_card_review_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='review_date',
            field=models.DateField(default=datetime.datetime(2023, 8, 8, 10, 50, 48, 31358)),
        ),
        migrations.AlterField(
            model_name='deck',
            name='number',
            field=models.IntegerField(default=1, unique=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(6)]),
        ),
    ]
