# Generated by Django 4.2.4 on 2023-08-07 07:30

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0004_alter_card_review_date_alter_deck_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='review_date',
            field=models.DateField(default=datetime.datetime(2023, 8, 8, 11, 0, 16, 175095)),
        ),
    ]
