# Generated by Django 4.2.4 on 2023-08-08 11:54

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0005_alter_card_review_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='review_date',
            field=models.DateField(default=datetime.datetime(2023, 8, 8, 15, 24, 31, 868020)),
        ),
    ]
