# Generated by Django 4.2.4 on 2023-08-08 16:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0009_remove_card_deck_card_deck'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='card',
            name='deck',
        ),
        migrations.AddField(
            model_name='card',
            name='deck',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='cards.deck'),
            preserve_default=False,
        ),
    ]
