# Generated by Django 4.2.4 on 2023-08-08 16:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0010_remove_card_deck_card_deck'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='card',
            name='number',
        ),
    ]
